/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/
 
const bGround = require('fcc-express-bground');
// Nos importamos los routers
const jsfile1 = require('./route-parameters');
const jsfile2 = require('./query-parameters');
const jsfile3 = require('./post-request');
const jsfile4 = require('./dif-query-vs-post-params');

// Montamos el objeto app express del server
const express = require('express');
const app = express();

// Configuramos los routers
app.use(jsfile1);
app.use(jsfile2);
app.use(jsfile3);
app.use(jsfile4);

// middlewares static para servir archivos de las rutas staticas
app.use(express.static(__dirname + "/public")) 
app.use(express.static(__dirname + "/views")) 


if (!process.env.DISABLE_XORIGIN) {
  app.use((req, res, next) => {
    const allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    const origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

const port = process.env.PORT || 3000;
bGround.setupBackgroundApp(app, null, __dirname).listen(port, () => {
  bGround.log(`Node is listening on port ${port}...`);
});

/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

